site_name: yuselg
site_url: https://yuselg.github.io/docs/

docs_dir: docs
site_dir: ../docs

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue
      accent: blue
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - toc.integrate
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Links: links/index.md
  - Misc: misc/index.md
  - Tags: tags.md


plugins:
  - search
  - blog:
      blog_dir: links
  - tags
